import { Post } from '@/types';

export const initialPosts: Post[] = [
  {
    id: 'e1',
    type: 'experience',
    sections: [
      { label: '사건', emoji: '⚡', content: '팀 프레젠테이션 준비를 너무 늦게 시작해서 발표 전날 밤새 작업했습니다. 결국 자료를 완성하지 못한 채 발표에 임했어요.' },
      { label: '결과', emoji: '🌊', content: '발표는 엉망이었고 팀원들에게 큰 민폐를 끼쳤습니다. 며칠간 자책감과 미안함으로 힘들었어요.' },
      { label: '배운점', emoji: '🌱', content: '큰 과제는 반드시 작은 단계로 나눠서 미리 일정을 세워야 한다는 걸 몸으로 배웠습니다. 마감 일주일 전부터 시작하기로 다짐했어요.' },
    ],
    anonymous: true,
    author: '익명',
    likes: 24,
    likedByMe: true,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    isOwn: false,
  },
  {
    id: 'e2',
    type: 'experience',
    sections: [
      { label: '사건', emoji: '⚡', content: '팀원과 충분한 소통 없이 혼자 중요한 설계 결정을 내렸습니다. 모두가 동의할 거라고 가정했죠.' },
      { label: '결과', emoji: '🌊', content: '나중에 팀원들이 반대 의견을 내면서 처음부터 다시 설계해야 했습니다. 시간을 2배로 썼어요.' },
      { label: '배운점', emoji: '🌱', content: '아무리 확신이 있어도 팀 내 결정은 함께 논의해야 한다는 걸 배웠습니다. 독단적인 확신은 오히려 위험해요.' },
    ],
    anonymous: false,
    author: '김도현',
    likes: 15,
    likedByMe: false,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    isOwn: false,
  },
  {
    id: 'e3',
    type: 'experience',
    sections: [
      { label: '사건', emoji: '⚡', content: '열심히 준비한 사이드 프로젝트를 6개월 만에 포기했습니다. 사용자가 전혀 없었어요.' },
      { label: '결과', emoji: '🌊', content: '6개월의 시간과 비용이 날아갔습니다. 한동안 무기력함을 느꼈어요.' },
      { label: '배운점', emoji: '🌱', content: '빌드하기 전에 먼저 시장 검증을 해야 한다는 걸 뼈저리게 배웠습니다. MVP부터 시작하는 것의 가치를 알았어요.' },
    ],
    anonymous: true,
    author: '익명',
    likes: 67,
    likedByMe: false,
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    isOwn: true,
  },
  {
    id: 'a1',
    type: 'attitude',
    sections: [
      { label: '상황', emoji: '🌟', content: '처음으로 팀장 역할을 맡았는데, 경험이 없어 무엇부터 해야 할지 막막했습니다.' },
      { label: '태도', emoji: '💪', content: '모르는 것을 인정하고, 팀원 한 명 한 명에게 솔직하게 배움을 요청했습니다. 매일 짧은 체크인 미팅을 열었어요.' },
      { label: '성과', emoji: '🏆', content: '팀원들이 오히려 더 적극적으로 도와줬고, 프로젝트를 성공적으로 마무리했습니다. 신뢰가 실력을 이긴다는 걸 배웠어요.' },
    ],
    anonymous: false,
    author: '이수진',
    likes: 31,
    likedByMe: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isOwn: false,
  },
  {
    id: 'a2',
    type: 'attitude',
    sections: [
      { label: '상황', emoji: '🌟', content: '상사로부터 예상치 못한 혹독한 피드백을 받았습니다. 공개적인 자리에서 제 작업이 비판받았어요.' },
      { label: '태도', emoji: '💪', content: '감정적으로 반응하고 싶었지만, 우선 깊게 숨을 쉬고 "구체적으로 어떤 부분이 문제인가요?"라고 물었습니다.' },
      { label: '성과', emoji: '🏆', content: '피드백의 핵심을 이해하고 수정한 결과물이 훨씬 좋아졌습니다. 그 상사가 나중에 따로 칭찬해줬어요.' },
    ],
    anonymous: false,
    author: '박준혁',
    likes: 42,
    likedByMe: false,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    isOwn: false,
  },
  {
    id: 'a3',
    type: 'attitude',
    sections: [
      { label: '상황', emoji: '🌟', content: '3개월 동안 공들인 프로젝트가 방향이 바뀌어 전면 재작업 지시를 받았습니다.' },
      { label: '태도', emoji: '💪', content: '좌절했지만 팀장에게 방향 변경의 이유를 물어보고, 새로운 방향에서 내가 기여할 수 있는 부분을 먼저 찾았어요.' },
      { label: '성과', emoji: '🏆', content: '새 방향이 실제로 더 나은 결과를 냈고, 제 제안이 핵심 기능으로 채택됐습니다.' },
    ],
    anonymous: true,
    author: '익명',
    likes: 18,
    likedByMe: false,
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    isOwn: false,
  },
];
